services:
  textboard:
    build: ./textboard
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - textboard_data:/app/data

  monitor:
    build: ./monitoring
    ports:
      - "5001:5001"
    restart: always

#  reverse-proxy:
#    image: nginx:alpine
#    container_name: reverse-proxy
#    volumes:
#      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "8080:80"            # public entrypoint (so http://SERVER:8080)
#    depends_on:
#      - textboard
#      - monitor
#    restart: always
#   healthcheck:
#      test: ["CMD-SHELL", "wget -qO- http://localhost/healthz || exit 1"]
#      interval: 10s
#      timeout: 3s
#      retries: 3


volumes:
  textboard_data:

